### PR TITLE
fix(xref/lib/search): find text variations for concepts

### LINKED ISSUE #216: xref not matching plural terms
## Description of problem

**What happened (e.g., it crashed)?:**

Given:
```HTML 
    <section id="abstract" data-cite="dom">
      <p>[=elements=] [=attributes=]</p>
    </section>
```

**Expected behavior (e.g., it shouldn't crash):**

Expected xref to work on those, as they are just concepts.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #216

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Seems like there could be more clashes now. Need to check for regressions in real specs

**Comment by marcoscaceres** [comment]
This is definitely a bug... I can't link anything in plural form at the moment.

**Comment by marcoscaceres** [comment]
Anything I can do to help move this one along?

**Comment by sidvishnoi** [comment]
Superseded by #221

**Pull request closed without merging**
